export const TOOLS = {
  LOGIN: "LOGIN",

  OPEN_TABLE: "OPEN_TABLE",

  SELECT_CATEGORY: "SELECT_CATEGORY",

  ADD_ITEM: "ADD_ITEM",

  REMOVE_ITEM: "REMOVE_ITEM",

  CLEAR_CART: "CLEAR_CART",

  SEND_TO_KITCHEN: "SEND_TO_KITCHEN",

  VIEW_OPEN_CHECKS: "VIEW_OPEN_CHECKS",

  VIEW_CLOSED_CHECKS: "VIEW_CLOSED_CHECKS",

  CLOSE_CHECK: "CLOSE_CHECK",

  CHECKOUT: "CHECKOUT",

  PAY: "PAY",

  CONFIRM_MODIFIERS: "CONFIRM_MODIFIERS",

  SHOW_TABLES: "SHOW_TABLES",

  LOGOUT: "LOGOUT",

  SELECT_CHECK: "SELECT_CHECK",
};
